// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrometheusAppWebApi.Repository.Concrete.EntityFramework;

namespace PrometheusAppWebApi.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateOfBirth = new DateTime(1982, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marysmith@gmail.com",
                            Name = "Mary",
                            PhoneNumber = "5462356564",
                            Surname = "Smith"
                        },
                        new
                        {
                            UserId = 2,
                            DateOfBirth = new DateTime(1975, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "saralongway@gmail.com",
                            Name = "Sara",
                            PhoneNumber = "5612356452",
                            Surname = "Longway"
                        },
                        new
                        {
                            UserId = 3,
                            DateOfBirth = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnhastings@gmail.com",
                            Name = "John",
                            PhoneNumber = "5264589568",
                            Surname = "Hastings"
                        },
                        new
                        {
                            UserId = 4,
                            DateOfBirth = new DateTime(1988, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "samgalloway@gmail.com",
                            Name = "Sam",
                            PhoneNumber = "5145362585",
                            Surname = "Galloway"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
